---
Name: responsiveimages
---
SilverStripe\Assets\Image:
  extensions:
    - Heyday\ResponsiveImages\ResponsiveImageExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - Heyday\ResponsiveImages\ResponsiveImageExtension
